# Generated by Django 2.0.6 on 2018-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=30)),
                ('degree', models.CharField(default='BS Student', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('graduated', models.BooleanField()),
                ('company', models.CharField(max_length=30)),
            ],
        ),
    ]
