# Generated by Django 2.0.6 on 2018-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='picpath',
            field=models.FilePathField(default='/static'),
        ),
    ]
