# Generated by Django 2.0.6 on 2018-06-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_members_picpath'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
