# Generated by Django 2.0.6 on 2018-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180620_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picpath',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='/dd', upload_to='web/members/image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
