# Generated by Django 2.0.6 on 2018-06-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_education_experience_lab_lecture_post_professor_project_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='web/members/image/base.jpg', upload_to='web/members/image'),
        ),
    ]
