# Generated by Django 2.0.6 on 2018-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180623_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
