# Generated by Django 2.0.6 on 2018-06-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180627_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='state',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
