# Generated by Django 2.0.6 on 2018-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_professor_image'),
        ('web', '0007_auto_20180627_1307'),
    ]

    operations = [
    ]
