# Generated by Django 2.0.6 on 2018-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180628_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
    ]
