# Generated by Django 2.0.6 on 2018-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
