# Generated by Django 2.0.6 on 2018-07-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
